create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start 1 increment 1;
create table geo_coordinate (id int8 not null, lat float8, lon float8, primary key (id));
create table hop (id int8 not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins int4, location_coordinates_id int8 not null, primary key (id));
create table hop_arrival (id int8 not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id int8, primary key (id));
create table parcel (id int8 not null, delivery_status int4, tracking_id varchar(255), weight float4, fk_recipient int8 not null, fk_sender int8 not null, primary key (id));
create table parcel_future_hops (parcel_entity_id int8 not null, future_hops_id int8 not null);
create table parcel_visited_hops (parcel_entity_id int8 not null, visited_hops_id int8 not null);
create table recipient (id int8 not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id int8 not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id int8 not null, level int4, primary key (id));
create table warehouse_next_hop (id int8 not null, traveltime_mins int4, hop_id int8, fk_warehouse int8, primary key (id));
alter table if exists parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table if exists parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table if exists hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table if exists hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table if exists parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table if exists parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table if exists parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table if exists parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table if exists parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table if exists parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table if exists warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table if exists warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start with 1 increment by 1;
create table geo_coordinate (id bigint not null, lat double, lon double, primary key (id));
create table hop (id bigint not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins integer, location_coordinates_id bigint not null, primary key (id));
create table hop_arrival (id bigint not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id bigint, primary key (id));
create table parcel (id bigint not null, delivery_status integer, tracking_id varchar(255), weight float, fk_recipient bigint not null, fk_sender bigint not null, primary key (id));
create table parcel_future_hops (parcel_entity_id bigint not null, future_hops_id bigint not null);
create table parcel_visited_hops (parcel_entity_id bigint not null, visited_hops_id bigint not null);
create table recipient (id bigint not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id bigint not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id bigint not null, level integer, primary key (id));
create table warehouse_next_hop (id bigint not null, traveltime_mins integer, hop_id bigint, fk_warehouse bigint, primary key (id));
alter table parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
create sequence hibernate_sequence start with 1 increment by 1;
create table geo_coordinate (id bigint not null, lat double, lon double, primary key (id));
create table hop (id bigint not null, code varchar(255) not null, description varchar(255), hop_type varchar(255), location_name varchar(255), processing_delay_mins integer, location_coordinates_id bigint not null, primary key (id));
create table hop_arrival (id bigint not null, code varchar(255), date_time timestamp, description varchar(255), parcel_id bigint, primary key (id));
create table parcel (id bigint not null, delivery_status integer, tracking_id varchar(255), weight float, fk_recipient bigint not null, fk_sender bigint not null, primary key (id));
create table parcel_future_hops (parcel_entity_id bigint not null, future_hops_id bigint not null);
create table parcel_visited_hops (parcel_entity_id bigint not null, visited_hops_id bigint not null);
create table recipient (id bigint not null, city varchar(255), country varchar(255), name varchar(255), postal_code varchar(255), street varchar(255), primary key (id));
create table truck (id bigint not null, number_plate varchar(255), region_geo_json varchar(255), primary key (id));
create table warehouse (id bigint not null, level integer, primary key (id));
create table warehouse_next_hop (id bigint not null, traveltime_mins integer, hop_id bigint, fk_warehouse bigint, primary key (id));
alter table parcel_future_hops add constraint UK_5n3ioygccxg6y7co1loncxsib unique (future_hops_id);
alter table parcel_visited_hops add constraint UK_5ckrxkay580275dbafce4itcy unique (visited_hops_id);
alter table hop add constraint FKpg83abvdhaacpduxapkgiv5o0 foreign key (location_coordinates_id) references geo_coordinate;
alter table hop_arrival add constraint FKqtmp1ixploh586cskjcelpgyr foreign key (parcel_id) references parcel;
alter table parcel add constraint FKsrfcic9pbkl7sjsa10ppn276d foreign key (fk_recipient) references recipient;
alter table parcel add constraint FK8ymexse0blcr45s32sgeqikr5 foreign key (fk_sender) references recipient;
alter table parcel_future_hops add constraint FK5nm446utyyro698bsn3mscxku foreign key (future_hops_id) references hop_arrival;
alter table parcel_future_hops add constraint FK8y8vv3tmpull0peypaqpaku9h foreign key (parcel_entity_id) references parcel;
alter table parcel_visited_hops add constraint FKg49unpi43j8aqkmb0qc5vloii foreign key (visited_hops_id) references hop_arrival;
alter table parcel_visited_hops add constraint FKb2dsbqgyhe4quhcsdefmhsupw foreign key (parcel_entity_id) references parcel;
alter table warehouse_next_hop add constraint FKqpru1kapbquxa0xbqv11rye8p foreign key (hop_id) references hop;
alter table warehouse_next_hop add constraint FK94ctln2p7xbccr1pqh00487sq foreign key (fk_warehouse) references warehouse;
